HTTPLocalServerPractice/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('practice_app.urls'))
]

practice_app/urls.py
from django.urls import path, include
from practice_app.views import csv_file_upload_view, list_csv_content_view, csv_row_delete_view, CSVEditRowView, \
    CSVAddNewRowView, backup_to_s3_view, restore_from_s3_view

app_name = 'practice_app'
urlpatterns = [
    path('', list_csv_content_view, name='index'),
    path('upload_csv/', csv_file_upload_view, name='upload_csv'),
    path('add_new_row/', CSVAddNewRowView.as_view(), name='add_new_row'),
    path('backup_to_s3/', backup_to_s3_view, name='backup_to_s3'),
    path('restore_from_s3/', restore_from_s3_view, name='restore_from_s3'),
    path('<int:objectId>/', include([
        path('edit/', CSVEditRowView.as_view(), name='edit_row'),
        path('delete/', csv_row_delete_view, name='delete_row'),
    ]))
]

practice_app/models.py
from django.db import models

GENDER_CHOICES = (
    ('male', 'Male'),
    ('female', 'Female'),
    ('other', 'Other')
)


class MuseumAPICSV(models.Model):
    """
    Model to store CSV data.
    """
    objectId = models.IntegerField(primary_key=True)
    isHighlight = models.BooleanField()
    accessionNumber = models.CharField(max_length=50)
    accessionYear = models.CharField(max_length=50)
    isPublicDomain = models.BooleanField()
    primaryImage = models.CharField(max_length=50, null=True, blank=True)
    primaryImageSmall = models.CharField(max_length=50, null=True, blank=True)
    additionalImages = models.CharField(max_length=50, null=True, blank=True)
    department = models.CharField(max_length=50)
    objectName = models.CharField(max_length=50)
    title = models.CharField(max_length=50, null=True, blank=True)
    culture = models.CharField(max_length=50, null=True, blank=True)
    period = models.CharField(max_length=50, null=True, blank=True)
    dynasty = models.CharField(max_length=50, null=True, blank=True)
    reign = models.CharField(max_length=50, null=True, blank=True)
    portfolio = models.CharField(max_length=50, null=True, blank=True)
    artistRole = models.CharField(max_length=50, null=True, blank=True)
    artistPrefix = models.CharField(max_length=50, null=True, blank=True)
    artistDisplayName = models.CharField(max_length=50, null=True, blank=True)
    artistDisplayBio = models.CharField(max_length=200, null=True, blank=True)
    artistSuffix = models.CharField(max_length=50, null=True, blank=True)
    artistAlphaSort = models.CharField(max_length=50, null=True, blank=True)
    artistNationality = models.CharField(max_length=50, null=True, blank=True)
    artistBeginDate = models.CharField(max_length=50, null=True, blank=True)
    artistEndDate = models.CharField(max_length=50, null=True, blank=True)
    artistGender = models.CharField(max_length=20,
                                    choices=GENDER_CHOICES,
                                    default='male'
                                    )
    artistWikidata_URL = models.CharField(max_length=50, null=True, blank=True)
    artistULAN_URL = models.CharField(max_length=50, null=True, blank=True)
    objectDate = models.CharField(max_length=50, null=True, blank=True)
    objectBeginDate = models.CharField(max_length=50, null=True, blank=True)
    objectEndDate = models.CharField(max_length=50, null=True, blank=True)
    medium = models.CharField(max_length=50, null=True, blank=True)
    dimensions = models.CharField(max_length=50, null=True, blank=True)
    measurements = models.CharField(max_length=50, null=True, blank=True)
    creditLine = models.CharField(max_length=50, null=True, blank=True)
    geographyType = models.CharField(max_length=50, null=True, blank=True)
    city = models.CharField(max_length=50, null=True, blank=True)
    state = models.CharField(max_length=50, null=True, blank=True)
    county = models.CharField(max_length=50, null=True, blank=True)
    country = models.CharField(max_length=50, null=True, blank=True)
    region = models.CharField(max_length=50, null=True, blank=True)
    subregion = models.CharField(max_length=50, null=True, blank=True)
    locale = models.CharField(max_length=50, null=True, blank=True)
    locus = models.CharField(max_length=50, null=True, blank=True)
    excavation = models.CharField(max_length=50, null=True, blank=True)
    river = models.CharField(max_length=50, null=True, blank=True)
    classification = models.CharField(max_length=50, null=True, blank=True)
    rightsAndReproduction = models.CharField(max_length=50, null=True, blank=True)
    linkResource = models.CharField(max_length=50, null=True, blank=True)
    metadataDate = models.DateTimeField(null=True, blank=True)
    repository = models.CharField(max_length=50, null=True, blank=True)
    objectURL = models.CharField(max_length=50, null=True, blank=True)
    tags = models.CharField(max_length=50, null=True, blank=True)
    objectWikidata_URL = models.CharField(max_length=50, null=True, blank=True)
    isTimelineWork = models.BooleanField()
    galleryNumber = models.IntegerField(null=True, blank=True)
    constituentID = models.FloatField(null=True, blank=True)
    role = models.CharField(max_length=50, null=True, blank=True)
    name = models.CharField(max_length=50, null=True, blank=True)
    constituentULAN_URL = models.CharField(max_length=50, null=True, blank=True)
    constituentWikidata_URL = models.CharField(max_length=50, null=True, blank=True)
    gender = models.CharField(max_length=20,
                              choices=GENDER_CHOICES,
                              default='male'
                              )

    def save(self, *args, **kwargs):
        # self.metadataDate = parse_datetime(self.metadataDate)
        super(MuseumAPICSV, self).save(*args, **kwargs)

    def __str__(self):
        return str(self.objectId)

practice_app/forms.py
from io import TextIOWrapper, StringIO

import pandas as pd
from django import forms

from practice_app.models import MuseumAPICSV


class UploadCSVFileForm(forms.Form):
    """
    Form that allows the user to upload CSV file.
    """
    csv_file = forms.FileField(label='Upload CSV File')

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(UploadCSVFileForm, self).__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super(UploadCSVFileForm, self).clean()
        f = TextIOWrapper(self.request.FILES['csv_file'].file, encoding='utf-8')
        f.seek(0)

        csv_data = StringIO(f.read())

        df = pd.read_csv(csv_data, sep=",")
        # validate_csv(df)

        # first line (only) contains additional information about the event
        # let's validate that against its form definition

        return cleaned_data


class EditCSVRowForm(forms.ModelForm):
    metadataDate = forms.DateTimeField(
        error_messages={'invalid': 'date time must be of following format yyyy-mm-dd hh:mm:ss'}
    )

    class Meta:
        model = MuseumAPICSV
        exclude = ('objectId',)

    def clean(self):
        cleaned_data = super(EditCSVRowForm, self).clean()
        for key, value in cleaned_data.items():
            if key != 'metadataDate':
                if value is None:
                    cleaned_data[key] = ''

        return cleaned_data


class CreateCSVRowForm(forms.ModelForm):
    class Meta:
        model = MuseumAPICSV
        fields = '__all__'

    def clean(self):
        cleaned_data = super(CreateCSVRowForm, self).clean()
        for key, value in cleaned_data.items():
            if value is None:
                cleaned_data[key] = ''
            if key == 'galleryNumber' or key == 'constituentID':
                cleaned_data[key] = -1

        return cleaned_data

practice_app/views.py
"""
    Contains all the views for performing CRUD operations.
"""

import csv
import datetime
from io import TextIOWrapper

from botocore.exceptions import ClientError
from django.conf import settings
from django.core.exceptions import ValidationError
from django.forms.models import model_to_dict
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.http import require_http_methods
from django.views.generic import UpdateView, CreateView
from museum_api.utils import Converter

from practice_app.forms import UploadCSVFileForm, CreateCSVRowForm, EditCSVRowForm
from practice_app.models import MuseumAPICSV
from .utils import get_s3_client, get_sns_client


@require_http_methods(["GET"])
def list_csv_content_view(request):
    """
    Homepage of the website. Displays uploaded CSV file in table form.
    :param request: HTTPRequest object
    :return: HttpResponse object
    """
    if request.method == 'GET':
        headings = [f.name for f in MuseumAPICSV._meta.get_fields()]
        museum_api_csv_objs = MuseumAPICSV.objects.all()

        return render(request, 'practice_app/index.html', {
            'headings': headings,
            'csv_objs': museum_api_csv_objs,
            })


def csv_to_museum_api_objects(csv_content):
    list_of_dicts = list(csv.DictReader(csv_content.split('\n')))
    rows = [x.values() for x in list_of_dicts]
    objects = []

    for row in rows:
        columns = []
        for column in row:
            columns.append(column)
        objects.append(MuseumAPICSV(
            pk=columns[0],
            isHighlight=columns[1],
            accessionNumber=columns[2],
            accessionYear=columns[3],
            isPublicDomain=columns[4],
            primaryImage=columns[5],
            primaryImageSmall=columns[6],
            additionalImages=columns[7] or '',
            department=columns[8] or '',
            objectName=columns[9] or '',
            title=columns[10] or '',
            culture=columns[11] or '',
            period=columns[12] or '',
            dynasty=columns[13] or '',
            reign=columns[14] or '',
            portfolio=columns[15] or '',
            artistRole=columns[16] or '',
            artistPrefix=columns[17] or '',
            artistDisplayName=columns[18] or '',
            artistDisplayBio=columns[19] or '',
            artistSuffix=columns[20] or '',
            artistAlphaSort=columns[21] or '',
            artistNationality=columns[22] or '',
            artistBeginDate=columns[23] or '',
            artistEndDate=columns[24] or '',
            artistGender=columns[25] or 'm',
            artistWikidata_URL=columns[26] or '',
            artistULAN_URL=columns[27] or '',
            objectDate=columns[28] or '',
            objectBeginDate=columns[29] or '',
            objectEndDate=columns[30] or '',
            medium=columns[31] or '',
            dimensions=columns[32] or '',
            measurements=columns[33] or '',
            creditLine=columns[34] or '',
            geographyType=columns[35] or '',
            city=columns[36] or '',
            state=columns[37] or '',
            county=columns[38] or '',
            country=columns[39] or '',
            region=columns[40] or '',
            subregion=columns[41] or '',
            locale=columns[42] or '',
            locus=columns[43] or '',
            excavation=columns[44] or '',
            river=columns[45] or '',
            classification=columns[46] or '',
            rightsAndReproduction=columns[47],
            linkResource=columns[48] or '',
            metadataDate=columns[49] or '',
            repository=columns[50] or '',
            objectURL=columns[51] or '',
            tags=columns[52] or '',
            objectWikidata_URL=columns[53] or '',
            isTimelineWork=columns[54] or '',
            galleryNumber=columns[55] or -1,
            constituentID=columns[56] or -1,
            role=columns[57] or '',
            name=columns[58] or '',
            constituentULAN_URL=columns[59] or '',
            constituentWikidata_URL=columns[60] or '',
            gender=columns[61] or 'male',
        ))
    return objects


class CSVEditRowView(UpdateView):
    """
    View that allows the user to edit a CSV row.
    """
    queryset = MuseumAPICSV.objects.all()
    pk_url_kwarg = 'objectId'
    form_class = EditCSVRowForm
    template_name = 'practice_app/edit_or_create_csv_row.html'
    success_url = reverse_lazy('practice_app:index')
    required_css_class = 'required'

    def get_success_url(self):
        try:
            sns = get_sns_client()
            obj = self.get_object()

            sns.publish(
                TopicArn=settings.SNS_TOPIC_ARN,
                Subject=f'[CRUD App] Row id {str(obj.pk)} updated - {datetime.datetime.now()}',
                Message=f'Hi,\n\nA row with id {str(obj.pk)} has been updated\n\nRegards,\nXYZ'
            )
        except ClientError as cl_e:
            pass
        return super(CSVEditRowView, self).get_success_url()

    @method_decorator(require_http_methods(["GET", "POST"]))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class CSVAddNewRowView(CreateView):
    """
     View that allows the user to add new row to the CSV.
    """
    queryset = MuseumAPICSV.objects.all()
    form_class = CreateCSVRowForm
    template_name = 'practice_app/edit_or_create_csv_row.html'
    success_url = reverse_lazy('practice_app:index')
    required_css_class = 'required'

    def get_success_url(self):
        try:
            sns = get_sns_client()

            sns.publish(
                TopicArn=settings.SNS_TOPIC_ARN,
                Subject=f'[CRUD App] New Row has been added - {datetime.datetime.now()}',
                Message='Hi,\n\nA new row has been added to the CSV\n\nRegards,\nXYZ'
            )
        except ClientError as cl_e:
            pass

        return super().get_success_url()

    @method_decorator(require_http_methods(["GET", "POST"]))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


@require_http_methods(["GET", "POST"])
def csv_row_delete_view(request, objectId):
    """
    View that allows the user to upload CSV file to the server.
    :param request: HTTPRequest object
    :param objectId: id of the row to be deleted.
    :return: HttpResponse object
    """
    if request.method == 'GET':
        return HttpResponse(status=200)

    if request.method == 'POST':
        row_obj = get_object_or_404(MuseumAPICSV, pk=objectId)
        row_id = row_obj.pk

        row_obj.delete()
        try:
            sns = get_sns_client()

            sns.publish(
                TopicArn=settings.SNS_TOPIC_ARN,
                Subject=f'[CRUD App] Row id {row_id} has been deleted - {datetime.datetime.now()}',
                Message=f'Hi,\n\nA row with id {row_id} has been successfully deleted\n\nRegards,\nXYZ'
            )
        except ClientError as cl_e:
            pass
        return redirect('practice_app:index')


@require_http_methods(["POST"])
def backup_to_s3_view(request):
    if request.method == 'POST':
        # MuseumAPICSV.
        file_name = 'museum_data.csv'
        list_of_dicts = []
        if MuseumAPICSV.objects.all().count() != 0:
            for obj in MuseumAPICSV.objects.all():
                list_of_dicts.append(model_to_dict(obj))
            Converter.convert_to_csv(list_of_dicts, file_name)
            try:
                sns = get_sns_client()
                sns.publish(
                    TopicArn=settings.SNS_TOPIC_ARN,
                    Subject=f'[CRUD App] Backup initiated - {datetime.datetime.now()}',
                    Message='Hi,\n\nA backu p to S3 has been successfully initiated.\n\nRegards,\nXYZ'
                )

                s3 = get_s3_client('default')
                bucket_name = settings.BACKUP_BUCKET_NAME

                s3.upload_file(file_name, bucket_name, file_name)

                sns.publish(
                    TopicArn=settings.SNS_TOPIC_ARN,
                    Subject=f'[CRUD App] Backup Completed - {datetime.datetime.now()}',
                    Message=f'Hi,\n\nA backu p to S3 has been successfully completed'
                            '\n\nRegards,\nXYZ'
                )

                return JsonResponse({
                    'success': 'Backup Completed successfully'
                })
            except ClientError as c_e:
                return JsonResponse({
                    'error': f'Backup failed :{c_e.args[-1]}'
                })
        else:
            return JsonResponse({
                'error': 'Nothing to backup'
            })


def restore_from_s3_view(request):
    if request.method == 'POST':
        file_name = 'museum_data.csv'
        bucket_name = settings.BACKUP_BUCKET_NAME

        try:
            s3 = get_s3_client('default')
            s3.download_file(bucket_name, file_name, file_name)

            sns = get_sns_client()

            sns.publish(
                TopicArn=settings.SNS_TOPIC_ARN,
                Subject=f'[CRUD App] Restoration Completed - {datetime.datetime.now()}',
                Message='Hi,\n\nData has been successfully restored.\n\nRegards,\nXYZ'
            )
        except ClientError as cl_e:
            if int(cl_e.response['Error']['Code']) == 404:
                return JsonResponse({
                    'error': 'Nothing to restore'
                })

        try:
            with open(file_name, 'r') as file:
                objects = csv_to_museum_api_objects(file.read())
                MuseumAPICSV.objects.bulk_create(
                    objects,
                    ignore_conflicts=True
                )
                return JsonResponse({

templates/practice_app/csv_deleted.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ file_name }} Deleted successfully</h1>
{% endblock %}

templates/practice_app/csv_detail.html
{% extends "base.html" %}
{% load static %}


{% block content %}
  <div class="container">
    <h1 class="text-center">Showing content of {{ file_name }}</h1>
    <table class="table">
    <thead>
      <tr>
        {% for heading in headings %}
            <th scope="col">{{ heading }}</th>
        {% endfor %}
      </tr>
    </thead>
    <tbody>
        {% for row in rows %}
          <tr>
              {% for column in row %}
                <td>{{ column }}</td>
              {% endfor %}
          </tr>
        {% endfor %}
    </tbody>
  </table>
  </div>
{% endblock %}

templates/practice_app/csv_upload.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <h1>
                    Upload CSV file
                </h1>
                <form method="post" enctype="multipart/form-data">{% csrf_token %}
                    {{ form }}
                    {% if form.errors %}
                        {% for field in form %}
                            {% for error in field.errors %}
                                <div class="alert alert-danger">
                                    <strong>{{ error|escape }}</strong>
                                </div>
                            {% endfor %}
                        {% endfor %}
                        {% for error in form.non_field_errors %}
                            <div class="alert alert-danger">
                                <strong>{{ error|escape }}</strong>
                            </div>
                        {% endfor %}
                    {% endif %}
                    <input class="btn btn-primary" type="submit" value="Submit">
                </form>
            </div>
        </div>
    </div>

{% endblock %}

templates/practice_app/edit_or_create_csv_row.html
{% extends "base.html" %}
{% load static %}

{% block head_extra %}
    <link rel="stylesheet" href="{% static 'practice_app/css/edit_or_create_csv_row.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <form method="post" enctype="multipart/form-data">{% csrf_token %}
            {{ form.non_field_errors }}
                <div class="row">
                    {% for field in form.visible_fields %}
                        <div class="col-md-6 form-group">
                            <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
<!--                            <input class="form-control" type="text" value="{% if field.value %}{{ field.value }}{% else %} {% endif %}">-->
                            {{ field }}
                            {{ field.errors }}
                        </div>
                    {% endfor %}
                </div>
            <input style="float:right" class="btn btn-primary" type="submit" value="Save">
        </form>
    </div>
    <script>
        for(let element of document.querySelectorAll('input[type=text]')) {
            if(element.value === undefined || element.value === '') {
                element.value = '';
            }
        }
    </script>
{% endblock %}

templates/practice_app/index.html
{% extends "base.html" %}
{% load static %}

{% block head_extra %}
  <link rel="stylesheet" href="{% static 'practice_app/css/index.css' %}" />
{% endblock %}

{% block content %}
<div class="modal fade" id="spinnerModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Backing Up</h5>

      </div>
      <div class="modal-body">
        <div class="loader"></div>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="spinnerRestoreModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Restoring backup</h5>

      </div>
      <div class="modal-body">
        <div class="loader"></div>
      </div>
    </div>
  </div>
</div>
  <div id="restoreBackupModal" class="modal" tabindex="-1" role="dialog">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">Restore data from S3</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <p>Are you sure you want to restore data to S3?</p>
            <br />
            <p class="text-danger">Note: This will overwrite the current data.</p>
          </div>
          <div class="modal-footer">
            <button id="confirm-restore-btn" data-backdrop="static" data-keyboard="false" data-toggle="modal" data-target="#spinnerRestoreModal" data-dismiss="modal" type="button" class="btn btn-primary">Confirm</button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
    <div id="backupModal" class="modal" tabindex="-1" role="dialog">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">Backup data to S3</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <p>Are you sure you want to backup the data to S3?</p>
          </div>
          <div class="modal-footer">
            <button id="confirm-backup-btn" data-backdrop="static" data-keyboard="false" data-toggle="modal" data-target="#spinnerModal" data-dismiss="modal" type="button" class="btn btn-primary">Confirm</button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
  <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
    <a class="navbar-brand" href="#">Crud App</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        </li>

      </ul>
      <button data-toggle="modal" data-target="#backupModal" id="backup-to-s3-btn" class="btn btn-outline-success my-2 my-sm-0 mx-1" type="button">Backup data to S3</button>
      <button data-toggle="modal" data-target="#restoreBackupModal" id="restore-from-s3-btn" class="btn btn-outline-primary my-2 my-sm-0 mx-1" type="button">Restore data from S3</button>
    </div>
  </nav>

  <div class="container">
    {% if csv_objs %}
      <table style="margin-top: 76px" class="table table-striped">
      <thead class="thead-dark">
        <tr>
          {% for heading in headings %}
              <th scope="col">{{ heading }}</th>
          {% endfor %}
          <th scope="col">Delete</th>
          <th scope="col">Edit</th>
        </tr>
      </thead>
      <tbody>
          {% for obj in csv_objs %}
            <tr>
              <td>{{ obj.objectId }}</td>
              <td>{{ obj.isHighlight }}</td>
              <td>{{ obj.accessionNumber }}</td>
              <td>{{ obj.accessionYear }}</td>
              <td>{{ obj.isPublicDomain }}</td>
              <td>{{ obj.primaryImage }}</td>
              <td>{{ obj.primaryImageSmall }}</td>
              <td>{{ obj.additionalImages }}</td>
              <td>{{ obj.department }}</td>
              <td>{{ obj.objectName }}</td>
              <td>{{ obj.title }}</td>
              <td>{{ obj.culture }}</td>
              <td>{{ obj.period }}</td>
              <td>{{ obj.dynasty }}</td>
              <td>{{ obj.reign }}</td>
              <td>{{ obj.portfolio }}</td>
              <td>{{ obj.artistRole }}</td>
              <td>{{ obj.artistPrefix }}</td>
              <td>{{ obj.artistDisplayName }}</td>
              <td>{{ obj.artistDisplayBio }}</td>
              <td>{{ obj.artistSuffix }}</td>
              <td>{{ obj.artistAlphaSort }}</td>
              <td>{{ obj.artistNationality }}</td>
              <td>{{ obj.artistBeginDate }}</td>
              <td>{{ obj.artistEndDate }}</td>
              <td>{{ obj.artistGender }}</td>
              <td>{{ obj.artistWikidata_URL }}</td>
              <td>{{ obj.artistULAN_URL }}</td>
              <td>{{ obj.objectDate }}</td>
              <td>{{ obj.objectBeginDate }}</td>
              <td>{{ obj.objectEndDate }}</td>
              <td>{{ obj.medium }}</td>
              <td>{{ obj.dimensions }}</td>
              <td>{{ obj.measurements }}</td>
              <td>{{ obj.creditLine }}</td>
              <td>{{ obj.geographyType }}</td>
              <td>{{ obj.city }}</td>
              <td>{{ obj.state }}</td>
              <td>{{ obj.county }}</td>
              <td>{{ obj.country }}</td>
              <td>{{ obj.region }}</td>
              <td>{{ obj.subregion }}</td>
              <td>{{ obj.locale }}</td>
              <td>{{ obj.locus }}</td>
              <td>{{ obj.excavation }}</td>
              <td>{{ obj.river }}</td>
              <td>{{ obj.classification }}</td>
              <td>{{ obj.rightsAndReproduction }}</td>
              <td>{{ obj.linkResource }}</td>
              <td>{{ obj.metadataDate }}</td>
              <td>{{ obj.repository }}</td>
              <td>{{ obj.objectURL }}</td>
              <td>{{ obj.tags }}</td>
              <td>{{ obj.objectWikidata_URL }}</td>
              <td>{{ obj.isTimelineWork }}</td>
              <td>{{ obj.galleryNumber }}</td>
              <td>{{ obj.constituentID }}</td>
              <td>{{ obj.role }}</td>
              <td>{{ obj.name }}</td>
              <td>{{ obj.constituentULAN_URL }}</td>
              <td>{{ obj.constituentWikidata_URL }}</td>
              <td>{{ obj.gender }}</td>
              <td>
                <form method="post" action="{% url 'practice_app:delete_row' obj.objectId %}">{% csrf_token %}
                  <button class="btn btn-danger" type="submit">Delete</button>
                </form>
              </td>
              <td><a class="btn btn-primary" href="{% url 'practice_app:edit_row' obj.objectId %}">Edit</a></td>
            </tr>
          {% endfor %}
      </tbody>
    </table>
    <a class="btn btn-primary" href="{% url 'practice_app:add_new_row' %}">Add New Row</a>
    {% else %}
      <div style="margin-top: 75px" class="alert alert-warning text-center">No data to display! Please Upload a file.</div>
      <div class="row">
        <div class="col-md-12 d-flex justify-content-center">
          <a class="btn btn-primary d-flex" href="{% url 'practice_app:upload_csv' %}">Upload CSV File</a>
        </div>
      </div>

    {% endif %}
  </div>

  <script>
        let backup_to_s3_url = window.origin+"{% url 'practice_app:backup_to_s3' %}";
        let restore_from_s3_url = window.origin+"{% url 'practice_app:restore_from_s3' %}";
  </script>
  <script src="{% static 'practice_app/js/index.js' %}"></script>
{% endblock %}